#PyBot.py
#03.02.2013 by Georg Dorndorf under Creative Common License
#
#Feel free to enhance the code or rewrite it but please always mention me.

import pickle, random

# Loads the lexicon data which was generated by trainer.py.
a = open('lexicon','rb')
successorlist = pickle.load(a)
a.close()
# 
def nextword(a):
    if a in successorlist and len(successorlist[a]) > 0:
        return random.choice(successorlist[a])
    else:
        return 'ein'
speech=''

# initiate the whole programm 
while speech != 'quit':
    speech = raw_input('>')                # 
    s = random.choice(speech.split())      # 
    response = ''                          #
#   
	while True:
        neword = nextword(s)              # 
        response += ' ' + neword          # 
        s = neword						  #
        if neword[-1] in '.':
            break
    print response